"""Importable presentation text about Python."""

PRESENTATION_SCRIPT = [
    "Good morning/afternoon everyone. Today, I'm going to give you a comprehensive overview of Python — one of the most popular and versatile programming languages in the world. By the end of this presentation, you'll understand what Python is, why it's so popular, and where it's used.",
    "Let's start with the basics. Python is a high-level, interpreted, general-purpose programming language. It was created by a Dutch programmer named Guido van Rossum and was first released in 1991. Python is widely known for being beginner-friendly, highly readable, and incredibly versatile — which is why it has become the go-to language for millions of developers worldwide.",
    "Python has a rich history. It all started in 1989 when Guido van Rossum wanted to create a language that was easy to read and use. The first version was released in 1991. Over the years, Python 2 became widely popular, but in 2008, Python 3 was released with significant improvements. As of 2020, Python 2 is officially no longer supported, and the entire community has moved to Python 3.",
    "Here are the key features that make Python stand out. First, Python's syntax is very clean and easy to read — almost like writing English. It's an interpreted language, meaning you don't need to compile your code before running it. Python is dynamically typed, so you don't have to declare the data type of a variable. It fully supports object-oriented programming. It comes with a massive standard library — think of it as a toolbox with pre-built tools for almost any task. And finally, it's cross-platform and completely free and open source.",
    # "So why is Python so popular? Well, it's consistently ranked as one of the most popular programming languages in the world. It's an excellent language for beginners because of its simple and intuitive syntax. The Python community is enormous — meaning there are thousands of third-party libraries, forums, and resources available. Python is at the forefront of cutting-edge technologies like Artificial Intelligence, Machine Learning, and Data Science. And because of all this, there's a huge demand for Python developers in the job market.",
    # "Python is incredibly versatile. Let me walk you through some of its major applications. In web development, frameworks like Django and Flask power millions of websites. In data science, libraries like Pandas and NumPy are industry standards. For machine learning and AI, TensorFlow and PyTorch are built primarily for Python. Python is heavily used for automation and web scraping with tools like Selenium and BeautifulSoup. You can even build games with Pygame, desktop apps with Tkinter, and perform cybersecurity tasks. It truly is a language for every purpose.",
    # "Let's talk about how Python actually works. When you write Python code and run it, the Python interpreter first converts your source code into an intermediate form called bytecode. This bytecode is then executed by the Python Virtual Machine, or PVM. Unlike languages like C or Java, you don't need to manually compile your code — Python does it all automatically. The default implementation is CPython, which is written in C. There are also other implementations like Jython for Java platforms and PyPy, which focuses on speed.",
]


def get_presentation_script() -> list[str]:
    """Return a copy of the presentation paragraphs."""
    return PRESENTATION_SCRIPT.copy()
